"""Remove spec and material_nature from OrderRegistration

Revision ID: 0b6bbfe52f33
Revises: c616904e8d71
Create Date: 2025-10-18 14:00:44.271131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6bbfe52f33'
down_revision = 'c616904e8d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.drop_column('specifications')
        batch_op.drop_column('material_nature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_nature', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('specifications', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
