"""Create WorkOrderDemand table

Revision ID: 161c50b7c195
Revises: a3b816fd055e
Create Date: 2025-10-15 20:40:31.532425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161c50b7c195'
down_revision = 'a3b816fd055e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('material_description', sa.String(length=255), nullable=True),
    sa.Column('operation_description', sa.String(length=255), nullable=True),
    sa.Column('parent_material_description', sa.String(length=255), nullable=True),
    sa.Column('required_date', sa.DateTime(), nullable=False),
    sa.Column('bulk_material', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'part_number', name='_order_part_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_demand')
    # ### end Alembic commands ###
