"""Add warehouse_location_id to OrderRegistration model

Revision ID: 1e56bd09d71a
Revises: 56d00f411066
Create Date: 2025-10-24 13:11:56.282737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e56bd09d71a'
down_revision = '56d00f411066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_location_id', sa.Integer(), nullable=True, comment='儲位ID'))
        batch_op.create_foreign_key('fk_order_registration_warehouse_location', 'warehouse_locations', ['warehouse_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_registration_warehouse_location', type_='foreignkey')
        batch_op.drop_column('warehouse_location_id')

    # ### end Alembic commands ###
