"""Add lead_time to Part model

Revision ID: 255f5aee1c85
Revises: 9e045d7078e3
Create Date: 2025-10-18 17:58:07.595221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255f5aee1c85'
down_revision = '9e045d7078e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        # 1. Add the column as nullable first
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True, comment='採購前置期 (天)'))

    # 2. Update existing rows to set a default value (e.g., 5)
    op.execute("UPDATE parts SET lead_time = 5 WHERE lead_time IS NULL")

    with op.batch_alter_table('parts', schema=None) as batch_op:
        # 3. Alter the column to be non-nullable
        batch_op.alter_column('lead_time',
               existing_type=sa.Integer(),
               nullable=False,
               existing_comment='採購前置期 (天)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('lead_time')

    # ### end Alembic commands ###
