"""Add user_id to InventoryTransaction for user tracking

Revision ID: 42a0f8370efd
Revises: add5068f1305
Create Date: 2025-11-12 13:08:39.374008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a0f8370efd'
down_revision = 'add5068f1305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人員ID'))
        batch_op.create_foreign_key('fk_inventory_transactions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_transactions_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
