"""Add nullable warehouse_location_id to Order model

Revision ID: 56d00f411066
Revises: 5dc2c902c774
Create Date: 2025-10-24 13:03:57.237644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d00f411066'
down_revision = '5dc2c902c774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_warehouse_location', 'warehouse_locations', ['warehouse_location_id'], ['id'])
        batch_op.drop_column('location_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_order_warehouse_location', type_='foreignkey')
        batch_op.drop_column('warehouse_location_id')

    # ### end Alembic commands ###
