"""Move reorder_point and safety_stock to CurrentInventory

Revision ID: 5a6c0dc08fa3
Revises: 255f5aee1c85
Create Date: 2025-10-22 12:14:10.882654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6c0dc08fa3'
down_revision = '255f5aee1c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_stock', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=False, server_default='0'))

    # Data migration step: Copy values from parts to current_inventory
    # We need to use op.execute for data manipulation in Alembic
    connection = op.get_bind()

    # Update current_inventory with values from parts
    connection.execute(sa.text("""
        UPDATE current_inventory
        SET
            safety_stock = (SELECT p.safety_stock FROM parts p WHERE p.id = current_inventory.part_id),
            reorder_point = (SELECT p.reorder_point FROM parts p WHERE p.id = current_inventory.part_id)
    """))

    # Now that data is copied, we can drop the columns from parts
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')
        batch_op.drop_column('safety_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_stock', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reorder_point', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')
        batch_op.drop_column('safety_stock')

    # ### end Alembic commands ###
