"""Add location to inventory transactions

Revision ID: 5dc2c902c774
Revises: 68452cb49610
Create Date: 2025-10-23 08:17:49.308642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc2c902c774'
down_revision = '68452cb49610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_transactions_warehouse_location_id', 'warehouse_locations', ['warehouse_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_transactions_warehouse_location_id', type_='foreignkey')
        batch_op.drop_column('warehouse_location_id')

    # ### end Alembic commands ###
