"""Support multi-location stock counts

Revision ID: 68452cb49610
Revises: 5a6c0dc08fa3
Create Date: 2025-10-23 07:51:36.824273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68452cb49610'
down_revision = '5a6c0dc08fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_location_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('_part_warehouse_uc'), type_='unique')
        batch_op.create_foreign_key('fk_current_inventory_warehouse_location_id', 'warehouse_locations', ['warehouse_location_id'], ['id'])

    with op.batch_alter_table('stock_count_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_location_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('_stock_count_part_uc'), type_='unique')
        batch_op.create_unique_constraint('_stock_count_part_location_uc', ['stock_count_id', 'part_id', 'warehouse_location_id'])
        batch_op.create_foreign_key('fk_stock_count_details_warehouse_location_id', 'warehouse_locations', ['warehouse_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_count_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_stock_count_part_location_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_stock_count_part_uc'), ['stock_count_id', 'part_id'])
        batch_op.drop_column('warehouse_location_id')

    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_part_warehouse_location_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_part_warehouse_uc'), ['part_id', 'warehouse_id'])
        batch_op.drop_column('warehouse_location_id')

    # ### end Alembic commands ###
