"""Add type column to Part model

Revision ID: 9e045d7078e3
Revises: 0b6bbfe52f33
Create Date: 2025-10-18 14:23:27.766959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e045d7078e3'
down_revision = '0b6bbfe52f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True, comment='類型'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
