"""Add location_code to order_history

Revision ID: a3b816fd055e
Revises: ad13c22353db
Create Date: 2025-10-15 15:33:00.542072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b816fd055e'
down_revision = 'ad13c22353db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_column('location_code')

    # ### end Alembic commands ###
