"""add_dds_and_moq_to_current_inventory

Revision ID: a53e094293d7
Revises: 98459b25fb35
Create Date: 2025-12-20 15:25:41.032844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53e094293d7'
down_revision = '98459b25fb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desired_days_of_stock', sa.Integer(), nullable=False, server_default='30', comment='預計存貨天數 (DDS)'))
        batch_op.add_column(sa.Column('moq', sa.Integer(), nullable=False, server_default='1', comment='最小訂購量 (MOQ)'))

    with op.batch_alter_table('stock_out_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_template_items_part'))
        batch_op.drop_index(batch_op.f('idx_template_items_template'))

    with op.batch_alter_table('stock_out_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_template_name_warehouse'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_out_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_template_name_warehouse'), ['name', 'warehouse_id'], unique=1)

    with op.batch_alter_table('stock_out_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_template_items_template'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_template_items_part'), ['part_id'], unique=False)

    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.drop_column('moq')
        batch_op.drop_column('desired_days_of_stock')

    # ### end Alembic commands ###
