"""Add priority field to OrderRegistration

Revision ID: c616904e8d71
Revises: weekly_order_system
Create Date: 2025-10-17 14:54:02.882218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c616904e8d71'
down_revision = 'weekly_order_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False, comment='申請優先級: normal, urgent'))
        batch_op.drop_index(batch_op.f('idx_cycle_sequence'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cycle_sequence'), ['cycle_id', 'item_sequence'], unique=False)
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
