"""Add quantity_received to OrderRegistration

Revision ID: e15538e1c3cb
Revises: 1e56bd09d71a
Create Date: 2025-10-24 19:19:16.096266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15538e1c3cb'
down_revision = '1e56bd09d71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping non-existent temporary table
    # op.drop_table('_alembic_tmp_current_inventory')
    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.alter_column('warehouse_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('_part_warehouse_location_uc', ['part_id', 'warehouse_location_id'])

    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_received', sa.Integer(), nullable=False, server_default='0', comment='已入庫數量'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_registrations', schema=None) as batch_op:
        batch_op.drop_column('quantity_received')

    with op.batch_alter_table('current_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('_part_warehouse_location_uc', type_='unique')
        batch_op.alter_column('warehouse_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_current_inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_on_hand', sa.INTEGER(), nullable=True),
    sa.Column('reserved_quantity', sa.INTEGER(), nullable=True),
    sa.Column('available_quantity', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('safety_stock', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('reorder_point', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('warehouse_location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_location_id'], ['warehouse_locations.id'], name=op.f('fk_current_inventory_warehouse_location_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'warehouse_location_id', name=op.f('_part_warehouse_location_uc'))
    )
    # ### end Alembic commands ###
